version: '3'

services:
  hugo:
    container_name: hugo
    image: dokurin/hugo
    ports:
      - 1313:1313
    volumes:
      - ${PWD}:/src
    command:
      - server
      - --bind=0.0.0.0
      - --buildDrafts
  post:
    container_name: post
    entrypoint: /bin/sh
    image: dokurin/hugo
    volumes:
      - ${PWD}:/src
    command: /src/script/new_post.sh
