version: 2.1
executors:
  hugo:
    docker:
      - image: dokurin/hugo
  firebase:
    docker:
      - image: andreysenov/firebase-tools:8.4.1-alpine
  makdownlint:
    docker:
      - image: 06kellyjac/markdownlint-cli:0.22.0-alpine
  eclint:
    docker:
      - image: "odannyc/eclint@sha256:6912a340ba87bdd2f747e678f4075b98dc58f225dcfedbf89dae59ae8adf3427"

jobs:
  lint_markdown:
    executor: makdownlint
    steps:
      - checkout
      - run:
          name: lint markdown
          command: markdownlint -c .markdownlint.json -i archetypes -i ./content/posts/helloworld .

  lint_editorconfig:
    executor: eclint
    steps:
      - checkout
      - run:
          name: lint editorconfig
          command: eclint check archetypes content README.md Dockerfile script

  build:
    executor: hugo
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: build hugo
          command: hugo
      - persist_to_workspace:
          root: .
          paths:
            - public
  deploy:
    executor: firebase
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: deploy to Firebase Hosting
          command: firebase deploy --project=${PROJECT_ID} --token=${FIREBASE_TOKEN}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - lint_markdown
      - lint_editorconfig
      - build:
          requires:
            - lint_markdown
            - lint_editorconfig
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
