version: 2.1
executors:
  hugo:
    docker:
      - image: dokurin/hugo
  firebase:
    docker:
      - image: andreysenov/firebase-tools:8.4.1-alpine

jobs:
  build:
    executor: hugo
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: build hugo
          command: hugo
      - persist_to_workspace:
          root: .
          paths:
            - public
  deploy:
    executor: firebase
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: deploy to Firebase Hosting
          command: firebase deploy --project=${PROJECT_ID} --token=${FIREBASE_TOKEN}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
